Work3
Irina996/itirod pull request #3
Opened 2022-03-13 17:19 UTC by Irina996

2022-03-14 10:44 UTC, katetushkan requested changes

2022-03-14 10:44 UTC, katetushkan commented on ReviewSite/header/__button/header__button.css
> +    float: right;
no floats.

2022-03-14 10:44 UTC, katetushkan commented on ReviewSite/header/__button/header__button.css
> +    font-size: medium;
use strict values.

2022-03-14 10:44 UTC, katetushkan commented on ReviewSite/header/header.css
> +    height: 70px;
it's better to use rem values, not px.

2022-03-14 10:44 UTC, katetushkan commented on ReviewSite/index.html
> +    <button class="header__button">Log out</button>
it should be <a>, cuz it will redirect u to another page

2022-03-14 10:44 UTC, katetushkan commented on ReviewSite/index.html
> +    <button class="header__button">Your account</button>
same here.

2022-03-14 10:44 UTC, katetushkan commented on ReviewSite/index.html
> +        <h5 class="review__title">ReviewTitle</h5>
u can't use <h5> if u haven't use h4, h3, h2, h1 before

2022-03-14 10:44 UTC, katetushkan commented on ReviewSite/review-list/review-list.css
> +    width: calc(100% - 175px);
hmmm? why did u do that?

2022-03-14 10:44 UTC, katetushkan commented on ReviewSite/review-list/review-list.css
> +    float: right;
no floats

2022-03-14 10:44 UTC, katetushkan commented on ReviewSite/search-panel/__button/search-panel__button.css
> +    width: 4em;
why u use em here?

2022-03-14 10:44 UTC, katetushkan commented on ReviewSite/search-panel/search-panel.css
> +}
<img width="1440" alt="Screenshot 2022-03-14 at 11 44 07" src="https://user-images.githubusercontent.com/43992068/158156784-add3e55a-caca-4763-936f-199c42c274c7.png">
It doesn't look like ur mockup(

2022-03-21 09:12 UTC, katetushkan approved these changes
Rn It's an 8. If u wanna more, u need to add focus and active styles to ur button and link. Let me know if u wanna upgrade.

2022-03-21 09:12 UTC, katetushkan commented on ReviewSite/review/__description/review__description.css
> +    width: 45vw;
don't take values from viewport, t can be tricky, if it's container it should be depending on a content inside, if no set it via px or rem

2022-03-21 09:20 UTC, Irina996 commented
I will upgrade

2022-03-25 13:51 UTC, Irina996 commented
please select the functions that I need to do so that I can start working on lab 4

2022-03-28 12:19 UTC, katetushkan commented
> please select the functions that I need to do so that I can start working on lab 4

2) Search and filter reviews by title/tags/group/rate<br/>
 3) Like review<br/>
 4) Comment review<br/>


9 is urs. for the 3rd work.

2022-03-28 12:32 UTC, katetushkan reviewed
.

2022-04-24 09:39 UTC, merged